export const DAYS_OF_WEEK = [
  "Lunes",
  "Martes",
  "Miércoles",
  "Jueves",
  "Viernes",
  "Sábado",
  "Domingo",
];

export const MUSCLE_GROUPS = [
  "Pecho",
  "Espalda",
  "Hombros",
  "Biceps",
  "Triceps",
  "Piernas",
  "Glúteos",
  "Abdominales",
  "PSOAS",
  "Isometricos",
];

export const EXERCISES_BY_MUSCLE_GROUP = {
  Piernas: [
    "Curl femorales",
    "Sentadillas c/ TRX",
    "Extensión de rodillas Sillón cuadriceps",
    "Sentadillas c/ barra",
    "Sentadillas sumo",
    "Sentadillas single",
    "Sentadillas búlgaras",
    "Sentadillas c/ land mine",
    "Estocadas split",
    "Estocadas laterales",
    "Sentadillas estáticas",
    "Sentadillas copa",
    "Sentadillas c/pulso",
    "Sentadillas c/ press",
    "Sentadillas sissy",
    "Prensa hack - variantes",
    "Sentadillas c/ step",
    "Curl Nórdico y variaciones",
    "Subida al Cajon unilateral",
    "Buenos dias",
  ],
  Glúteos: [
    "Extensión de cadera patada atrás parado",
    "Extension de cadera patada arriba",
    "Cadera puente",
    "Hip trhust",
    "Aperturas de rodillas acostado de lado c/ banda",
  ],
  "Abductores y aductores": [
    "Aperturas de piernas c/ tobilleras de lado",
    "Acostado c/ tobilleras de frente",
    "Abductores parado c/disco",
    "Aductores sentado c/ pelota",
    "Abductores c/ banda parado",
  ],
  Femorales: [
    "Curl femorales en maquina",
    "Good morning",
    "Peso muerto rumano c/ barra",
    "Peso muerto rumano c/ mancuernas",
    "Peso muerto rumano a 1 pierna",
  ],
  Gemelos: [
    "Elevación de talones parado c/ s Peso",
    "Elevación de talones sentado",
    "Elevación de talones c/ hack",
  ],
  Pecho: [
    "Press bco plano c/ barra",
    "Press bco plano c/ mancuernas",
    "Aperturas bco plano",
    "Empuje arriba y al centro bco plano ( repite en inclinado)",
    "Pull over bco plano c/ barra",
    "Pull over bco plano c/ mancuernas",
    "Press bco plano a 45° ( repite en inclinado)",
    "Press bco plano a 1 mano",
    "Flexiones de brazos",
    "Vuelos en piso",
    "Cross over a 1 mano c/ polea",
    "Press bco inclinado c/ barra",
    "Press bco inclinado c/ mancuernas",
    "Aperturas",
    "Press bco inclinado agarre invertido",
    "Pull over bco inclinado c/ mancuerna o barra",
    "Elevaciones frontales c/ barra (supinacion)",
  ],
  Espalda: [
    "Polea alta pecho",
    "Polea tras nuca",
    "Espalda de cobra en bco plano",
    "Dominadas",
    "Polea a 1 mano",
    "Remo en trípode",
    "Remo medows c/ land mine",
    "Remo horizontal c/apoyo",
    "Remo Polea baja",
    "Remo al pecho c/ land mine",
    "Remo renegado c/ mancuernas",
    "Espinales",
    "Espinales en bco",
    "Pull over en polea c/ soga",
    "Pull over en polea (pronacion)",
    "Pull over en bco plano c/ mancuerna",
    "Pull over fijo ( agarre columna elevo piernas y tronco)",
    "Remo c/ TRX",
    "Remo c/ barra a 45°",
    "Remo al mentón",
    "Elevaciones en 'Y' en bco inclinado c/ mancuernas",
    "Tiron al trapecio en polea c/ soga",
    "Elevación frontal parado c/ disco (sube hasta arriba de la cabeza)",
    "Remo parado c/ mancuernas",
    "Encogimiento Honey c/ barra",
    "Remo polea baja a 1 mano a 45°",
  ],
  Biceps: [
    "Curl parado c/ barra",
    "Curl parado c/ mancuernas",
    "Bco Scott",
    "Curl biceps bco inclinado",
    "Curl alternado c/ mancuernas",
    "Curl copa",
    "Curl martillo",
    "Curl invertido c/ barra",
    "Curl invertido c/ mancuernas",
    "Curl concentrados a 1 mano",
    "Curl Arnold",
    "Curl Arnold martillo",
    "Curl c/ polea baja",
    "Curl c/polea alta",
    "Curl de biceps c/arrastre c/ mancuernas",
    "Dominadas al mentón",
    "Curl 21",
    "Curl de biceps a 1 mano en bco Scott",
    "Curl araña en bco inclinado c/ mancuernas",
  ],
  Triceps: [
    "Extensión en polea (pronacion)",
    "Extensión en polea c/soga",
    "Extensión en polea alta de espalda",
    "Extensión en polea a 1 mano",
    "Press francés en bco plano c/ barra ( clase skull) y c/ mancuerna",
    "Extensión vertical a 1 mano",
    "Extensión vertical c/ mancuerna",
    "Empuje al centro en bco plano c/ barra ( agarre cerrado)",
    "Empuje frontal arriba sentado c/ barra",
    "Extensión de codos c/ apoyo",
    "Extensión de codos a la vez ( cuerpo en 45°)",
    "Fondo en bco",
    "Flexiones diamantes",
    "Flexiones en paralelas",
  ],
  Hombros: [
    "Press tras nuca c/ barra",
    "Vuelos laterales",
    "Vuelos frontales",
    "Press afuera y arriba c/ disco",
    "Pres afuera c/ disco",
    "Elevaciones frontales con Disco",
    "Vuelo laterale a 1 brazo",
    "Posteriores ( pajaro)",
    "Posteriores parado a 45°",
    "Press Arnold c/ mancuernas",
    "Remo c/ Abducción",
    "Tiron a la cara en polea c/ soga",
    "Posteriores en polea a la nuca c/ soga",
    "Press de pala ( agarre neutro)",
    "Abraza caderas c/ mancuernas",
    "Press militar parado c/ barra",
    "Press militar sentado c/ mancuernas",
    "Elevacion frontal parado c/ barra supino",
    "Press en 'V' invertida",
    "Press a 1 brazo c/ land mine",
    "Elevación en bco inclinado c/ mancuernas Aperturas la vez supino",
    "Remo al mentón c/ barra",
    "Vuelo lateral a 1 brazo acostado de lado",
    "Qué me importa",
    "Elevaciones en Y en bco inclinado c/ mancuernas",
  ],
  Abdominales: [
    "Abs sentado en bco rodillas al pecho",
    "Abs twis",
    "Abs mariposa",
    "Crunch cruzados",
    "Crunch toco talones",
    "Crunch en bco",
    "Crunch altos",
    "Crunch en polea",
    "Abs colgado",
  ],
  PSOAS: ["Elevaciones de piernas alternado", "Tijera de piernas", "Variantes"],
  Isometricos: [
    "Planchas baja",
    "Plancha alta",
    "Plancha invertida",
    "Plancha lateral",
  ],
};
