export const DAYS_OF_WEEK = [
  "Lunes",
  "Martes",
  "Miércoles",
  "Jueves",
  "Viernes",
  "Sábado",
  "Domingo",
];

export const MUSCLE_GROUPS = [
  "Pecho",
  "Espalda",
  "Hombros",
  "Biceps",
  "Triceps",
  "Piernas",
  "Core",
  "Glúteos",
  "Cardio",
];

export const EXERCISES_BY_MUSCLE_GROUP = {
  Pecho: [
    "Press de Banca",
    "Press Inclinado",
    "Press Declinado",
    "Aperturas con Mancuernas",
    "Fondos en Paralelas",
    "Press con Mancuernas",
    "Pullover",
    "Flexiones",
  ],
  Espalda: [
    "Dominadas",
    "Remo con Barra",
    "Remo con Mancuerna",
    "Jalones al Pecho",
    "Peso Muerto",
    "Remo en Polea Baja",
    "Hiperextensiones",
    "Pull-ups",
  ],
  Hombros: [
    "Press Militar",
    "Elevaciones Laterales",
    "Elevaciones Frontales",
    "Elevaciones Posteriores",
    "Press con Mancuernas",
    "Remo al Mentón",
    "Encogimientos",
    "Arnold Press",
  ],
  Biceps: [
    "Curl de Bíceps",
    "Curl Martillo",
    "Curl en Predicador",
    "Curl con Barra",
  ],
  Triceps: [
    "Press Francés",
    "Extensiones de Tríceps",
    "Fondos para Tríceps",
    "Patadas de Tríceps",
  ],
  Piernas: [
    "Sentadillas",
    "Prensa de Piernas",
    "Extensiones de Cuádriceps",
    "Curl Femoral",
    "Peso Muerto Rumano",
    "Zancadas",
    "Elevaciones de Gemelos",
    "Sentadilla Búlgara",
  ],
  Core: [
    "Abdominales",
    "Plancha",
    "Crunches",
    "Elevaciones de Piernas",
    "Russian Twists",
    "Mountain Climbers",
    "Bicicleta",
    "Dead Bug",
  ],
  Glúteos: [
    "Hip Thrust",
    "Sentadilla Sumo",
    "Peso Muerto Rumano",
    "Patadas de Glúteo",
    "Puente de Glúteo",
    "Caminata Lateral",
    "Sentadilla Búlgara",
    "Extensiones de Cadera",
  ],
  Cardio: [
    "Cinta de Correr",
    "Bicicleta Estática",
    "Elíptica",
    "Remo",
    "Burpees",
    "Jumping Jacks",
    "Escaladora",
    "HIIT",
  ],
};
